version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/serviceAccountKey.json
